"""add_historical_incident_knowledge_base

Revision ID: 8c159ca34051
Revises: e88cb9958742
Create Date: 2026-06-14 14:43:02.001429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c159ca34051'
down_revision: Union[str, Sequence[str], None] = 'e88cb9958742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_history',
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('rca_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_history_incident_id'), 'rca_history', ['incident_id'], unique=False)
    op.create_table('resolution_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_history_incident_id'), 'resolution_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_history_incident_id'), table_name='resolution_history')
    op.drop_table('resolution_history')
    op.drop_index(op.f('ix_rca_history_incident_id'), table_name='rca_history')
    op.drop_table('rca_history')
    op.drop_table('incident_history')
    # ### end Alembic commands ###
