"""add correlations table phase 10

Revision ID: bc6f4bc61f30
Revises: b7a7bd7126eb
Create Date: 2026-06-09 09:42:31.686341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc6f4bc61f30'
down_revision: Union[str, Sequence[str], None] = 'b7a7bd7126eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_anomaly_id', sa.Integer(), nullable=False),
    sa.Column('log_anomaly_id', sa.Integer(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=False),
    sa.Column('inferred_cause', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 100.0', name='chk_confidence_range'),
    sa.CheckConstraint('correlation_score >= 0.0 AND correlation_score <= 1.0', name='chk_correlation_score_range'),
    sa.ForeignKeyConstraint(['log_anomaly_id'], ['logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_anomaly_id'], ['anomalies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlations_id'), 'correlations', ['id'], unique=False)
    op.create_index(op.f('ix_correlations_log_anomaly_id'), 'correlations', ['log_anomaly_id'], unique=False)
    op.create_index(op.f('ix_correlations_metric_anomaly_id'), 'correlations', ['metric_anomaly_id'], unique=False)
    op.alter_column('anomalies', 'metric_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomalies', 'metric_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_correlations_metric_anomaly_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_log_anomaly_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_id'), table_name='correlations')
    op.drop_table('correlations')
    # ### end Alembic commands ###
